# Generated by Django 5.0.2 on 2024-03-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
